"""add mute field to cluster

Revision ID: 055f616a0bd0
Revises: 1adb63166a8a
Create Date: 2022-10-13 11:43:34.355898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055f616a0bd0'
down_revision = '1adb63166a8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('watch', sa.BOOLEAN(create_constraint=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clusters', 'watch')
    # ### end Alembic commands ###
