"""initial

Revision ID: 1adb63166a8a
Revises: 
Create Date: 2022-10-12 18:09:48.235578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1adb63166a8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockchains',
    sa.Column('id', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=127), nullable=False),
    sa.Column('tag', mysql.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag'),
    sa.UniqueConstraint('title')
    )
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('balance', mysql.NUMERIC(precision=2), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(create_constraint=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addresses',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('wallet', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('blockchain_id', mysql.SMALLINT(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['blockchain_id'], ['blockchains.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet', 'blockchain_id')
    )
    op.create_table('clusters',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=28), nullable=False),
    sa.Column('user_id', mysql.BIGINT(), nullable=True),
    sa.Column('chats', mysql.LONGTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clusters_addresses',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('cluster_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('address_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('watch', sa.BOOLEAN(create_constraint=True), nullable=True),
    sa.Column('address_name', mysql.VARCHAR(length=28), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clusters_addresses')
    op.drop_table('clusters')
    op.drop_table('addresses')
    op.drop_table('users')
    op.drop_table('blockchains')
    # ### end Alembic commands ###
