"""alert history 2

Revision ID: 2c88f1f817ee
Revises: 79fa2c8008dd
Create Date: 2022-10-20 14:51:59.788445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c88f1f817ee'
down_revision = '79fa2c8008dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_history',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(), nullable=True),
    sa.Column('blockchain', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('wallet', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('balance_delta', mysql.NUMERIC(precision=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_history')
    # ### end Alembic commands ###
