"""tx hash

Revision ID: 3a2cb585f244
Revises: 9386f662041f
Create Date: 2022-11-18 09:26:30.419168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a2cb585f244'
down_revision = '9386f662041f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchains', sa.Column('tx_link_template', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blockchains', 'tx_link_template')
    # ### end Alembic commands ###
