"""success add flag

Revision ID: 59b7c7d4b09a
Revises: e72533a52a23
Create Date: 2022-10-19 13:06:29.427203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b7c7d4b09a'
down_revision = 'e72533a52a23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('add_success', sa.BOOLEAN(create_constraint=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'add_success')
    # ### end Alembic commands ###
