"""alert history

Revision ID: 79fa2c8008dd
Revises: 59b7c7d4b09a
Create Date: 2022-10-20 14:41:16.696071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79fa2c8008dd'
down_revision = '59b7c7d4b09a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification_cost', mysql.NUMERIC(precision=2), nullable=False))
    op.add_column('users', sa.Column('notifications_remain', mysql.BIGINT(unsigned=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notifications_remain')
    op.drop_column('users', 'notification_cost')
    # ### end Alembic commands ###
