"""add field created at to alert history

Revision ID: 9386f662041f
Revises: 20186263e2a2
Create Date: 2022-10-21 09:34:39.533435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9386f662041f'
down_revision = '20186263e2a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_history', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_history', 'created_at')
    # ### end Alembic commands ###
