"""explorer info add

Revision ID: e72533a52a23
Revises: 055f616a0bd0
Create Date: 2022-10-14 15:20:07.898557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e72533a52a23'
down_revision = '055f616a0bd0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchains', sa.Column('explorer_link_template', mysql.VARCHAR(255), nullable=True))
    op.add_column('blockchains', sa.Column('explorer_title', mysql.VARCHAR(255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blockchains', 'explorer_title')
    op.drop_column('blockchains', 'explorer_link_template')
    # ### end Alembic commands ###
